### ISSUE TITLE
OS X crash when sending notification

### ISSUE THREAD

**Issue by RomanZhilich** [rinaldus/mail-notifier#6]
Hello.

I got the following crash on OS X 10.11 when there's unread letters:
```
Traceback (most recent call last):
  File "./mail-notifier.py", line 468, in <module>
    mail_check()
  File "./mail-notifier.py", line 414, in mail_check
    notify ("You have "+ str(mail_count) +" unread letters")
  File "./mail-notifier.py", line 442, in notify
    subprocess.Popen(['notify-send', programTitle, message])
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'notify-send': 'notify-send'
```

I might be missing some dependencies but the only one required according to Readme is PyQt5 which I have installed via Homebrew.

**Comment by rinaldus** [comment]
Please, check my last commit 6ccb04632b9fa2abb9223c254b3d1451b76e2bd1. It seems that OS X have not 'notify-send' command. I changed the way to send notifications. Now the program requires additional library [notify2](https://pypi.python.org/pypi/notify2) as dependency. Install it and it should be work.

**Comment by RomanZhilich** [comment]
Thanks for prompt response. I pulled latest changes, installed `notify2`, and now I get following error:
```
  File "/usr/local/lib/python3.6/site-packages/notify2.py", line 39, in <module>
    import dbus
ModuleNotFoundError: No module named 'dbus'
```
There are some people having similar problems i.e. https://stackoverflow.com/questions/37521162/how-solve-importerror-no-module-named-dbus
But none of the proposed solutions worked for me, including installing `dbus` package via Homebrew.

**Comment by rinaldus** [comment]
Try to install the program in [virtualenv](http://sourabhbajaj.com/mac-setup/Python/virtualenv.html). Follow the instructions to install virtualenv, activate it and install `PyQt5`, `notify2` and probably `dbus` inside of virtualenv.

**Comment by rinaldus** [comment]
> But none of the proposed solutions worked for me, including installing `dbus` package via Homebrew.

Did you try to install [dbus-python](https://pypi.python.org/pypi/dbus-python) via pip?

**Comment by RomanZhilich** [comment]
>Did you try to install dbus-python via pip?

Installation fails without clear reason and a lot of junk output. I'm trying to dig through logs..
It seems there was relevant package in Homebrew but it got removed at some point. There are some outdated instructions online that recommend installing `brew install homebrew/python/python-dbus
`
I'll try downloading sources and installing it manually

**Comment by RomanZhilich** [comment]
I've made some progress but it still doesn't work.
To properly use `notify2` on OS X you have to install `dbus` with Homebrew:
```
brew install pkg-config dbus dbus-glib  
brew services start dbus
```
Then:
```
pip3 install notify2 dbus-python
```

But I still have an error when trying to launch `mail-notifier.py`:
```
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NameHasNoOwner: Could not get owner of name 'org.freedesktop.Notifications': no such name
```
It seems that dbus service is not properly registered in the system. Other people had this problem https://github.com/fr31/spotifylyrics/issues/19#issuecomment-242543039 but no workaround as far as I can tell.

**Comment by rinaldus** [comment]
I made quick [fix](c025371c1b2daae86b8b32bc9ca3bf2c07fb43c5) to prevent crashing if OS notification is different than Linux. Baloon notification won't work, but it will print notification to console output (better, than nothing) instead and it won't crash. Please, test this commit.
I will continue to work on this problem, but I'm not sure, that I succeed to resolve it and it won't be soon.

**Comment by RomanZhilich** [comment]
>Please, test this commit.

It still crashes because right now notify2 initialization is the problem. You'll have to make it conditional, probably including `import notify2` which I'm not sure how to do...

>I will continue to work on this problem

I will also try to resolve service error and update this issue if I find a solution.

**Comment by rinaldus** [comment]
Ok, I came back to first notification method (which using `notify-send`), but added try: ... except: ... to prevent crashing. Please, check b04cb9a6ffc275b723caa402f21fe8e65256ad84, is it workable? You should see notification in terminal output instead of baloon.

**Comment by RomanZhilich** [comment]
Yes, this is working.
Thanks.

**Comment by rinaldus** [comment]
I have one idea how to solve this problem, but I need to install OS X in Virtual Box and understand how it works there. It will take some time.

**Comment by RomanZhilich** [comment]
Thanks, I'll keep an eye out for updates.
But I think this issue should be closed. The crash was a bug, and it's fixed now that you handle OS X notifications issue gracefully.
