### ISSUE TITLE
Cannot file configuration. You should give access to your mailbox

### ISSUE THREAD

**Issue by KOT040188** [rinaldus/mail-notifier#7]
Mail-notifier does not work. It displays the "Can not file configuration. You should give access to your mailbox".

**Comment by rinaldus** [comment]
Did you fill all credentials in settings window? Did you push button "Test connection"?

**Comment by KOT040188** [comment]
> Did you fill all credentials in settings window?

Yes

> Did you push button "Test connection"?

Yes, but when I did this the application was hanging and I had to close it forcibly.

**Comment by rinaldus** [comment]
Please, send me console output when it hangs.

**Comment by KOT040188** [comment]
`kot@kot-MS-7930:~$ /home/kot/bin/mail-notifier-3.01/mail-notifier.py
Invalid Context= "Panel" line for icon theme:  "/usr/share/icons/Numix-Circle/16/panel/"
Invalid Context= "Panel" line for icon theme:  "/usr/share/icons/Numix-Circle/16@2x/panel/"
Invalid Context= "Panel" line for icon theme:  "/usr/share/icons/Numix-Circle/22/panel/"
Invalid Context= "Panel" line for icon theme:  "/usr/share/icons/Numix-Circle/22@2x/panel/"
Invalid Context= "Panel" line for icon theme:  "/usr/share/icons/Numix-Circle/24/panel/"
Invalid Context= "Panel" line for icon theme:  "/usr/share/icons/Numix-Circle/24@2x/panel/"
Invalid Context= "Panel" line for icon theme:  "/home/kot/.local/share/icons/Numix/16/panel/"
Invalid Context= "Panel" line for icon theme:  "/usr/share/icons/Numix/16/panel/"
Invalid Context= "Panel" line for icon theme:  "/usr/share/icons/Numix/16@2x/panel/"
Invalid Context= "Panel" line for icon theme:  "/usr/share/icons/Numix/22/panel/"
Invalid Context= "Panel" line for icon theme:  "/home/kot/.local/share/icons/Numix/22@2x/panel/"
Invalid Context= "Panel" line for icon theme:  "/usr/share/icons/Numix/22@2x/panel/"
Invalid Context= "Panel" line for icon theme:  "/usr/share/icons/Numix/24/panel/"
Invalid Context= "Panel" line for icon theme:  "/home/kot/.local/share/icons/Numix/24@2x/panel/"
Invalid Context= "Panel" line for icon theme:  "/usr/share/icons/Numix/24@2x/panel/"
Invalid Context= "Notifications" line for icon theme:  "/usr/share/icons/Numix/48/notifications/"
Invalid Context= "Notifications" line for icon theme:  "/home/kot/.local/share/icons/Numix/48@2x/notifications/"
Invalid Context= "Notifications" line for icon theme:  "/usr/share/icons/Numix/48@2x/notifications/"
`
This is written in the console at startup. When it hangs, it does not write anything.

**Comment by KOT040188** [comment]
The application window suddenly responded. The console is still nothing new written. It still does not work.

**Comment by rinaldus** [comment]
Please, check this [commit](7822c3690bbe290ac2a4ce7fb9c73071d3991886). The program did not work when no accounts were created. I fixed it.

**Comment by KOT040188** [comment]
> Please, check this commit.

404

**Comment by rinaldus** [comment]
Last commit
7822c3690bbe290ac2a4ce7fb9c73071d3991886

**Comment by KOT040188** [comment]
What do I do with this?

**Comment by rinaldus** [comment]
Update the program to last commit.

**Comment by KOT040188** [comment]
How to do it? I'm a beginner user. I do not understand.

**Comment by rinaldus** [comment]
`git clone https://github.com/rinaldus/mail-notifier.git`
or download this archive: https://github.com/rinaldus/mail-notifier/archive/master.zip

For additional information, read this:
https://help.github.com/articles/cloning-a-repository
https://guides.github.com/

**Comment by KOT040188** [comment]
Nothing changed.

**Comment by rinaldus** [comment]
What mail server do you use? Check, whether it support IMAP protocol. And also check, that you input a valid login and password and use correct port.

**Comment by KOT040188** [comment]
https://yadi.sk/i/Rg7uV74n3PqWk5

> And also check, that you input a valid login and password and use correct port.

Which port is correct? I do not even know what a port is.

**Comment by rinaldus** [comment]
Enable IMAP protocol in your mailbox settings (in Gmail). Read this article to set a proper port.
https://support.google.com/mail/answer/7126229?hl=en

**Comment by KOT040188** [comment]
I use unity-mail. It does not need to enter a port…

**Comment by KOT040188** [comment]
Настроил по вашей ссылке https://yadi.sk/i/DHQWHbAM3PqYrb
But he still writes "Can not file configuration. You should give access to your mailbox".

**Comment by KOT040188** [comment]
https://yadi.sk/i/w3ou3JTk3PqZ78

**Comment by rinaldus** [comment]
Do you see a message "Connection was established successfully"? This means that set proper connection.

**Comment by KOT040188** [comment]
I see it. But I do not see the work of the application.

**Comment by KOT040188** [comment]
The error is still the same.

**Comment by rinaldus** [comment]
You should input `imap.googlemail.com` instead of `imap.gmail.com` in "mail server" field.
https://i.imgur.com/qKIZbNT.png
https://i.imgur.com/HCYb0zk.png

**Comment by KOT040188** [comment]
According to the link you gave me, has to be imap.gmail.com https://yadi.sk/i/7KaFJEg43PqdSb

**Comment by rinaldus** [comment]
Все вопросы к гуглу. Мне пришлось зарегистрировать тестовый почтовый ящик на Gmail.com, чтобы убедиться, что все работает.

**Comment by KOT040188** [comment]
Thank you. Difficult your application. I have unity mail. For configuration, not need port or server. Everything is just...
